apiVersion: v1
kind: Service
metadata:
  name: standup-counter
  namespace: standup-counter
  labels:
    app: standup-counter
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3001
      protocol: TCP
  selector:
    app: standup-counter
